---
# SECURITY
- name: Get Public IP
  ipify_facts:
  register: myIp
  ignore_errors: True

- name: "EC2: Create Security Group"
  ec2_group:
    name: "jenkins_secgrp"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    description: "jenkins"
    vpc_id: "vpc-e2258998"
    region: "{{ region | default('us-east-1') }}"
    purge_rules: false
    rules:
    - proto: tcp
      ports:
        - 22
        - 80
        - 443
        - 8080
      cidr_ip: "0.0.0.0/32"
    purge_tags: no
    tags: { Name: "jenkins_secgrp", BillTo: "client" }
  register: ec2_secgrp_jkns
  ignore_errors: False
  tags: create-all, ec2-security


- name: "EC2: Create SSH Key"
  ec2_key:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    name: "jenkins"
    region: "{{ region | default('us-east-1') }}"
    state: present
    force: yes
  register: ec2_sshkey_jkns
  ignore_errors: no
  tags: create-all, ec2-security

- name: "EC2: Ensure SSH Key && Ansible Host File"
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items:
    - { path: "~/.ssh", mode: "0700", state: "directory", owner: "{{ ansible_user_id }}" }
    - { path: "~/.ssh/jenkins.pem", mode: "0700", state: "touch", owner: "{{ ansible_user_id }}" }
  when: ec2_sshkey_jkns.changed == True
  ignore_errors: True
  tags: create-all, ec2-security

- name: "EC2: Save Private Key (1/2)"
  shell: echo "" > ~/.ssh/jenkins.pem
  when: ec2_sshkey_jkns.changed == True
  tags: create-all, ec2-security
  ignore_errors: true

- name: "EC2: Save Private Key (2/2)"
  lineinfile:
    path: ~/.ssh/jenkins.pem
    regexp: "^.*"
    line: "{{ ec2_sshkey_jkns.key.private_key }}"
    state: present
    backup: yes
  when: ec2_sshkey_jkns.changed == True
  register: ec2_sshkey_jkns_status
  ignore_errors: False
  tags: create-all, ec2-security

- name: Get Jenkins Public Key
  shell: "ssh-keygen -y -f {{ ansible_user_dir }}/.ssh/jenkins.pem"
  register: pubkey_jkns_dict
  tags: create-all, ec2-security

- name: Set Fact
  set_fact:
    pubkey_jkns: "{{ pubkey_jkns_dict.stdout }}"
  tags: create-all, ec2-security

#- debug: var=pubkey_jkns
#- command: /bin/false


# PROVISION EC2 HOST
# 1) CENTOS 7 AMIs: https://wiki.centos.org/Cloud/AWS
# 2) discover AMIs: aws --region us-east-1 ec2 describe-images --owners aws-marketplace --filters Name=product-code,Values=aw0evgkw8e5c1q413zgy5pjce

- name: "EC2: Create Instance"
  ec2:
    id: "jenkins-idempotent-identifier001"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    key_name: "jenkins"
    group: "jenkins_secgrp"
    instance_type: "{{ ec2_type | default('t2.micro') }}"
    image: ami-02e98f78
    wait: yes
    wait_timeout: 600
    count: 1
    region: "{{ ec2_region | default('us-east-1') }}"
    zone: "{{ ec2_zone | default('us-east-1c') }}"
    instance_tags:
      Name: "jenkins"
      BillTo: "client"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 15
        delete_on_termination: True
    monitoring: no
    vpc_subnet_id: "{{ ec2_vpcId | default('subnet-bcca59db') }}"
    assign_public_ip: yes
  register: ec2_info_jkns
  tags: create-all, ec2-host
  notify:
    - DISCOVERY_JKNS

- debug: var=ec2_info_jkns

- name: Wait for SSH on jenkins
  wait_for:
    host: "{{ ec2_info_jkns.instances.0.public_ip }}"
    port: 22
    state: started
    delay: 10
    timeout: 300
  when: ec2_info_jkns.changed == true
  tags: create-all, ec2-host

- name: "EC2: Discover Public IP"
  ec2_instance_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: us-east-1
    filters:
      tag:Name: jenkins
      instance-state-name: "running"
      instance-state-code: "16"
  register: disc_jkns
  when: ec2_info_jkns.changed == false
  tags: create-all, ec2-host

- debug: 
    msg: "{{ ec2_info_jkns.instances.0.public_ip }} and {{ ec2_info_jkns.instances.0 }}"
  tags: create-all, ec2-host

- name: "EC2: Set ec2_pubIp_jkns Fact"
  set_fact:
    ec2_pubIp_jkns: "{{ disc_jkns.instances.0.public_ip_address }}"
  when: disc_jkns is not skipped
  tags: create-all, ec2-host

- name: "EC2: Set ec2_pubIp_jkns Fact"
  set_fact:
    ec2_pubIp_jkns: "{{ ec2_info_jkns.instances.0.public_ip }}"
  when: ec2_info_jkns is not skipped 
  tags: create-all, ec2-host

- name: "Set Fact"
  set_fact:
    ec2_prvKey: "{{ ansible_user_dir }}/.ssh/jenkins.pem"


- name: "Ensure Hosts File"
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items:
    - { path: "{{ ansible_user_dir }}/ANSIBLE", mode: "0755", state: "directory", owner: "{{ ansible_user_id }}" }
    - { path: "{{ ansible_user_dir }}/ANSIBLE/jenkins", mode: "0755", state: "touch", owner: "{{ ansible_user_id }}" }
  ignore_errors: False
  tags: create-all, ec2-security

- name: "LOCALHOST: Create host in {{ ansible_user_dir }}/ANSIBLE"
  lineinfile:
    path:  "{{ ansible_user_dir }}/ANSIBLE/jenkins"
    line: "{{ item.line }}"
  with_items:
    - { line: "[jenkins]" }
  tags: create-all, ec2-security

- debug: var=ec2_pubIp_jkns
  tags: create-all, ec2-host

- name: "LOCALHOST: Prepare for Jenkins Job Builder"
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items:
    - { path: "{{ ansible_user_dir }}/ANSIBLE/jenkins_jobs.ini", mode: "0755", state: "touch", owner: "{{ ansible_user_id }}" }
  tags: create-all

# jenkins job builder: https://docs.openstack.org/infra/jenkins-job-builder/execution.html#job-builder-section
- name: "LOCALHOST: Update jenkins_jobs.ini"
  blockinfile:
    path: "{{ ansible_user_dir }}/ANSIBLE/jenkins_jobs.ini"
    block: |
      [job_builder]
      ignore_cache=True
      keep_descriptions=False
      recursive=False
      allow_duplicates=False
      update=all

      [jenkins]
      query_plugins_info=False
      user=admin
      password={{ jenkins_admin_password | default('admin') }}
      url=http://{{ ec2_pubIp_jkns }}:8080/jenkins
  tags: create-all

- name: Update github_ci.yml IP Address
  lineinfile:
    path: ./jobs/github_ci.yml
    regexp: "^.*shell:.*"
    line: "      - shell: \"ssh -o StrictHostKeyChecking=no jenkins@{{ ec2_pubIp }} '/bin/bash /home/jenkins/github_ci.sh'\""
  tags: create-all

