---
# IMPORTANT: Ensure tags accross all plays and tasks are added to these discovery jobs
- name: DISCOVERY
  ec2_instance_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: us-east-1
    filters:
      tag:Name: notejam
      instance-state-name: "running"
      instance-state-code: "16"
  register: disc
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY"

- name: DISCOVERY
  debug:
    msg: "{{ disc.instances.0.public_ip_address }}"
  when: disc['instances'] is defined and (disc['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY"


- name: DISCOVERY
  set_fact:
    ec2_pubIp: "{{ disc.instances.0.public_ip_address }}"
  when: disc['instances'] is defined and (disc['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY"

- name: DISCOVERY
  add_host:
    name: "{{ ec2_pubIp }}"
    groups: notejam
    ansible_ssh_private_key_file: "~/.ssh/notejam.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_port: 22
    ansible_ssh_user: centos
  when: disc['instances'] is defined and (disc['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY"


- name: DISCOVERY_JKNS
  ec2_instance_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: us-east-1
    filters:
      tag:Name: jenkins
      instance-state-name: "running"
      instance-state-code: "16"
  register: disc_jkns
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY_JKNS"

- name: DISCOVERY_JKNS
  debug:
    msg: "{{ disc_jkns.instances.0.public_ip_address }}"
  when: disc_jkns['instances'] is defined and (disc_jkns['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY_JKNS"

- name: DISCOVERY_JKNS
  set_fact:
    ec2_pubIp_jkns: "{{ disc_jkns.instances.0.public_ip_address }}"
  when: disc_jkns['instances'] is defined and (disc_jkns['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY_JKNS"

- name: DISCOVERY_JKNS
  add_host:
    name: "{{ ec2_pubIp_jkns }}"
    groups: jenkins
    ansible_ssh_private_key_file: "~/.ssh/jenkins.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_port: 22
    ansible_ssh_user: centos
  when: disc_jkns['instances'] is defined and (disc_jkns['instances']| length > 0)
  tags: discovery, create-all, ec2-host, ec2-security, os, app
  listen: "DISCOVERY_JKNS"

